site_name: X1cT34m Wiki
site_url: https://wiki.x1ct34m.com

repo_url: https://github.com/X1cT34m/wiki
repo_name: X1cT34m/wiki

copyright: Copyright &copy; 2016 - 2024 X1cT34m · <a href="https://beian.miit.gov.cn/" target="_blank" rel="noopener">苏ICP备2026008980号-1</a>

theme:
  name: material
  language: zh

  palette:
    primary: white

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.footer

  icon:
    repo: fontawesome/brands/github 

plugins:
  - search
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: false

nav:
  - Home:
    - 主页: index.md
    - 关于我们: about.md
    - 招新要求: join.md
  - Introduction:
    - 如何正确的提问: introduction/how-to-ask.md
    - CTF 介绍: introduction/ctf.md
    - 入门资料: introduction/docs.md
    - 新生赛事: introduction/ctf-events.md
    - 从 0 到 1: introduction/from-zero-to-one.md
    - 常见 QA: introduction/faq.md
  - Web:
    - 入门指南: web/guide.md
    - 常用工具: web/tools.md
  - Pwn:
    - 入门指南: pwn/guide.md
    - 常用工具: pwn/tools.md
  - Reverse:
    - 入门指南: reverse/guide.md
    - 常用工具: reverse/tools.md
  - Crypto:
    - 入门指南: crypto/guide.md
    - 常用工具: crypto/tools.md
  - Misc:
    - 入门指南: misc/guide.md
    - 常用工具: misc/tools.md
